### ISSUE TITLE
Fehlende Datei /wp-content/plugins/Fotorama-Leaflet-Elevation/build/fm_bundle/fm_main.js

### ISSUE THREAD

**Issue by hupe13** [MartinvonBerg/Fotorama-Leaflet-Elevation#1]
Hallo Martin,

im deutschen [Supportforum](https://de.wordpress.org/support/topic/gallerie-mit-karte-gallery-with-map/) wurde moniert, dass dein Plugin nicht funktionieren würde.  Ich habe es nach deiner Anleitung ebenfalls  installiert und erhalte denselben Fehler wie der Threadstarter: /wp-content/plugins/Fotorama-Leaflet-Elevation/build/fm_bundle/fm_main.js existiert nicht, Fehler 404.

Und es gibt auch php-Warnungen.

Viele der Komponenten in deinem Plugin kommen mir sehr bekannt vor. ;-)

Viele Grüße.
hupe13

**Comment by MartinvonBerg** [comment]
Das ist richtig. Der Fehler ist gefunden und wird mit dem nächsten Release bereinigt. Danke für den Hinweis.
