### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [MartinvonBerg/Fotorama-Leaflet-Elevation#2]
I would like to suggest changing the (default) tile URL, by removing the `{s}.`
See https://github.com/openstreetmap/operations/issues/737

Use (also) for documentation
[See where it is used](https://github.com/search?q=repo%3AMartinvonBerg%2FFotorama-Leaflet-Elevation+.tile.openstreetmap.org&type=code)

...and use direct HTTPS links for attribution. (unless some targeted devices do not support HTTPS)
`https://www.openstreetmap.org/`

**Comment by MartinvonBerg** [comment]
Will be solved with new version comming soon. Thanks for your hint!

**Comment by MartinvonBerg** [comment]
Solved with Release of V.031.0
